services:
  ha:
    image: homeassistant/home-assistant:2025.1
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./custom_components/robovac_mqtt:/config/custom_components/robovac_mqtt